### ISSUE TITLE
[Bug] press variant style apply time from Pressable widget seems to be longer than Material Buttons press effect

### ISSUE THREAD

**Issue by Maus3rSR** [conceptadev/mix#108] opened 2022-12-20 17:49 UTC
Hello,

Thank you for this awesome library.
Im still a beginner developer so sorry if I misunderstood something...

I tried a sample app to use your pressable widget
```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:mix/mix.dart';

Mix get pressableMix => Mix(
      elevation(8),
      padding(20),
      rounded(30),
      bgColor(Colors.white),
      border(
        color: Colors.black,
        width: 2,
      ),
      hover(
        border(
          color: Colors.green,
        ),
      ),
      press(
        elevation(1),
        border(
          color: Colors.green,
          width: 4,
        ),
      ),
    );

class BaseStyleButton extends StatelessWidget {
  const BaseStyleButton({super.key});

  @override
  Widget build(BuildContext context) {
    return Pressable(
      onPressed: () {
        stdout.write("BaseStyleButton pressed");
      },
      child: Box(
        mix: pressableMix,
        child: const TextMix('Button'),
      ),
    );
  }
}
```

and implement it in a sample app, along to a `TextButton`

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:ultrashot_design_system/component.dart';

void main() {
  runApp(const UltrashotApp());
}

class UltrashotApp extends StatelessWidget {
  const UltrashotApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ultrashot ALPHA',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const DesignSystemShowCase(),
    );
  }
}

class DesignSystemShowCase extends StatelessWidget {
  const DesignSystemShowCase({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Ultrashot Design System'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const BaseStyleButton(),
            TextButton(
              onPressed: () {
                stdout.write("BaseStyleButton pressed");
              },
              child: const Text('Button'),
            )
          ],
        ),
      ),
    );
  }
}
```

On my ANDROID 9 / SAMSUNG S8 (SM-G950F)

It seems that the press variant is applied on a longer press than the press effect of the material button.
I can see the debug message by pressing the button without be able to see the press variant applied. However the material button press effect is instant when I press it with the same tap pression.

**Comment by leoafarias** [comment] 2022-12-21 16:03
@Maus3rSR so if I understand correctly the issue is just the lag of the the onPresss function? We are using just a GestureDetector with the onTap property, will do some research to see what TextButton uses under the surface

**Comment by leoafarias** [comment] 2022-12-21 16:12
@Maus3rSR thanks for the clarification, will review

**Comment by leoafarias** [comment] 2022-12-21 19:34
@Maus3rSR I did some optimizations on the `Pressable`, there might be some API changes, I am thinking about implementing a `GestureBox` to try to replicate the `GestureDetector`

**Comment by leoafarias** [comment] 2022-12-21 19:43
Please test again once #109 is merged

**Comment by Maus3rSR** [comment] 2022-12-22 08:49
Im seeing it open and not merged on main, or should I pull another version with pub?

**Comment by leoafarias** [comment] 2022-12-22 22:14
@Maus3rSR if you can test that PR, and see if it fixes the issue it would be great

**Closed** 2023-09-13 07:37 UTC
Labels: bug
